<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PalabraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('palabras')->insert([
            ['descripcion' => "aceituna"],
            ['descripcion' => "aceituna verde"],
            ['descripcion' => "agua"],
            ['descripcion' => "ají amarillo"],
            ['descripcion' => "ajo"],
            ['descripcion' => "antitucho"],
            ['descripcion' => "apio"],
            ['descripcion' => "arroz"],
            ['descripcion' => "azúcar"],
            ['descripcion' => "café"],
            ['descripcion' => "camote"],
            ['descripcion' => "caramelo"],
            ['descripcion' => "carne molida"],
            ['descripcion' => "carne pescado"],
            ['descripcion' => "carne pollo"],
            ['descripcion' => "carne res"],
            ['descripcion' => "carne"],
            ['descripcion' => "causa"],
            ['descripcion' => "cebolla"],
            ['descripcion' => "cerveza"],
            ['descripcion' => "ceviche"],
            ['descripcion' => "chicha"],
            ['descripcion' => "chicha cusco"],
            ['descripcion' => "choclo"],
            ['descripcion' => "chocolate"],
            ['descripcion' => "chorizo"],
            ['descripcion' => "ciruela"],
            ['descripcion' => "coca cola"],
            ['descripcion' => "coco"],
            ['descripcion' => "col"],
            ['descripcion' => "culantro"],
            ['descripcion' => "durazno"],
            ['descripcion' => "emoliente"],
            ['descripcion' => "ensalada"],
            ['descripcion' => "espinaca"],
            ['descripcion' => "fanta"],
            ['descripcion' => "frejoles"],
            ['descripcion' => "fresa"],
            ['descripcion' => "frutas"],
            ['descripcion' => "galleta"],
            ['descripcion' => "gelatina"],
            ['descripcion' => "hamburguesa"],
            ['descripcion' => "helado"],
            ['descripcion' => "hot dog"],
            ['descripcion' => "huevo cusco"],
            ['descripcion' => "huevo"],
            ['descripcion' => "inca kola"],
            ['descripcion' => "jamón"],
            ['descripcion' => "ketchup"],
            ['descripcion' => "leche"],
            ['descripcion' => "lechuga"],
            ['descripcion' => "lentejas"],
            ['descripcion' => "limón"],
            ['descripcion' => "mandarina"],
            ['descripcion' => "mango"],
            ['descripcion' => "mantequilla"],
            ['descripcion' => "manzana"],
            ['descripcion' => "mayonesa"],
            ['descripcion' => "naranja"],
            ['descripcion' => "olluco"],
            ['descripcion' => "palta"],
            ['descripcion' => "pan"],
            ['descripcion' => "papa a la huancaína"],
            ['descripcion' => "papa rellena"],
            ['descripcion' => "papaya"],
            ['descripcion' => "papa"],
            ['descripcion' => "parrillada"],
            ['descripcion' => "pera"],
            ['descripcion' => "piña"],
            ['descripcion' => "plátano"],
            ['descripcion' => "queso"],
            ['descripcion' => "rocoto"],
            ['descripcion' => "sal"],
            ['descripcion' => "sandwich"],
            ['descripcion' => "sandía"],
            ['descripcion' => "sopa"],
            ['descripcion' => "tallarines"],
            ['descripcion' => "tamal"],
            ['descripcion' => "tomate"],
            ['descripcion' => "torta de cumpleaños"],
            ['descripcion' => "torta"],
            ['descripcion' => "tortilla"],
            ['descripcion' => "trigo"],
            ['descripcion' => "té"],
            ['descripcion' => "uva"],
            ['descripcion' => "verduras"],
            ['descripcion' => "vino"],
            ['descripcion' => "yuca"],
            ['descripcion' => "zanahoria"],
        ]);
    }
}
