<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PalabraCategoriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('palabra_categorias')->insert([
            ['categoria_id' => '4', 'palabra_id' => '1'],
            ['categoria_id' => '4', 'palabra_id' => '2'],
            ['categoria_id' => '5', 'palabra_id' => '3'],
            ['categoria_id' => '6', 'palabra_id' => '4'],
            ['categoria_id' => '4', 'palabra_id' => '5'],
            ['categoria_id' => '6', 'palabra_id' => '6'],
            ['categoria_id' => '3', 'palabra_id' => '7'],
            ['categoria_id' => '4', 'palabra_id' => '8'],
            ['categoria_id' => '4', 'palabra_id' => '9'],
            ['categoria_id' => '5', 'palabra_id' => '10'],
            ['categoria_id' => '4', 'palabra_id' => '11'],
            ['categoria_id' => '4', 'palabra_id' => '12'],
            ['categoria_id' => '4', 'palabra_id' => '13'],
            ['categoria_id' => '4', 'palabra_id' => '14'],
            ['categoria_id' => '4', 'palabra_id' => '15'],
            ['categoria_id' => '4', 'palabra_id' => '16'],
            ['categoria_id' => '4', 'palabra_id' => '17'],
            ['categoria_id' => '6', 'palabra_id' => '18'],
            ['categoria_id' => '4', 'palabra_id' => '19'],
            ['categoria_id' => '5', 'palabra_id' => '20'],
            ['categoria_id' => '6', 'palabra_id' => '21'],
            ['categoria_id' => '5', 'palabra_id' => '22'],
            ['categoria_id' => '5', 'palabra_id' => '23'],
            ['categoria_id' => '4', 'palabra_id' => '24'],
            ['categoria_id' => '4', 'palabra_id' => '25'],
            ['categoria_id' => '4', 'palabra_id' => '26'],
            ['categoria_id' => '2', 'palabra_id' => '27'],
            ['categoria_id' => '6', 'palabra_id' => '28'],
            ['categoria_id' => '2', 'palabra_id' => '29'],
            ['categoria_id' => '3', 'palabra_id' => '30'],
            ['categoria_id' => '3', 'palabra_id' => '31'],
            ['categoria_id' => '2', 'palabra_id' => '32'],
            ['categoria_id' => '5', 'palabra_id' => '33'],
            ['categoria_id' => '6', 'palabra_id' => '34'],
            ['categoria_id' => '3', 'palabra_id' => '35'],
            ['categoria_id' => '5', 'palabra_id' => '36'],
            ['categoria_id' => '4', 'palabra_id' => '37'],
            ['categoria_id' => '2', 'palabra_id' => '38'],
            ['categoria_id' => '2', 'palabra_id' => '39'],
            ['categoria_id' => '4', 'palabra_id' => '40'],
            ['categoria_id' => '4', 'palabra_id' => '41'],
            ['categoria_id' => '4', 'palabra_id' => '42'],
            ['categoria_id' => '4', 'palabra_id' => '43'],
            ['categoria_id' => '4', 'palabra_id' => '44'],
            ['categoria_id' => '4', 'palabra_id' => '45'],
            ['categoria_id' => '4', 'palabra_id' => '46'],
            ['categoria_id' => '5', 'palabra_id' => '47'],
            ['categoria_id' => '4', 'palabra_id' => '48'],
            ['categoria_id' => '4', 'palabra_id' => '49'],
            ['categoria_id' => '5', 'palabra_id' => '50'],
            ['categoria_id' => '3', 'palabra_id' => '51'],
            ['categoria_id' => '4', 'palabra_id' => '52'],
            ['categoria_id' => '2', 'palabra_id' => '53'],
            ['categoria_id' => '2', 'palabra_id' => '54'],
            ['categoria_id' => '2', 'palabra_id' => '55'],
            ['categoria_id' => '4', 'palabra_id' => '56'],
            ['categoria_id' => '2', 'palabra_id' => '57'],
            ['categoria_id' => '4', 'palabra_id' => '58'],
            ['categoria_id' => '2', 'palabra_id' => '59'],
            ['categoria_id' => '4', 'palabra_id' => '60'],
            ['categoria_id' => '2', 'palabra_id' => '61'],
            ['categoria_id' => '4', 'palabra_id' => '62'],
            ['categoria_id' => '6', 'palabra_id' => '63'],
            ['categoria_id' => '6', 'palabra_id' => '64'],
            ['categoria_id' => '2', 'palabra_id' => '65'],
            ['categoria_id' => '4', 'palabra_id' => '66'],
            ['categoria_id' => '6', 'palabra_id' => '67'],
            ['categoria_id' => '2', 'palabra_id' => '68'],
            ['categoria_id' => '2', 'palabra_id' => '69'],
            ['categoria_id' => '2', 'palabra_id' => '70'],
            ['categoria_id' => '4', 'palabra_id' => '71'],
            ['categoria_id' => '3', 'palabra_id' => '72'],
            ['categoria_id' => '4', 'palabra_id' => '73'],
            ['categoria_id' => '6', 'palabra_id' => '74'],
            ['categoria_id' => '2', 'palabra_id' => '75'],
            ['categoria_id' => '4', 'palabra_id' => '76'],
            ['categoria_id' => '4', 'palabra_id' => '77'],
            ['categoria_id' => '6', 'palabra_id' => '78'],
            ['categoria_id' => '2', 'palabra_id' => '79'],
            ['categoria_id' => '6', 'palabra_id' => '80'],
            ['categoria_id' => '6', 'palabra_id' => '81'],
            ['categoria_id' => '6', 'palabra_id' => '82'],
            ['categoria_id' => '4', 'palabra_id' => '83'],
            ['categoria_id' => '5', 'palabra_id' => '84'],
            ['categoria_id' => '2', 'palabra_id' => '85'],
            ['categoria_id' => '3', 'palabra_id' => '86'],
            ['categoria_id' => '5', 'palabra_id' => '87'],
            ['categoria_id' => '4', 'palabra_id' => '88'],
            ['categoria_id' => '3', 'palabra_id' => '89'],
        ]);
    }
}
