<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SeniaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('senias')->insert([
            ['palabra_id' => '1', 'imagen' => 'https://media.giphy.com/media/KxVnwZbx6qBoqofu1p/giphy.gif'],
            ['palabra_id' => '2', 'imagen' => 'https://media.giphy.com/media/l03t1o8i86kEShjOSJ/giphy.gif'],
            ['palabra_id' => '3', 'imagen' => 'https://media.giphy.com/media/Xd7tVyunGucr1blhmX/giphy.gif'],
            ['palabra_id' => '4', 'imagen' => 'https://media.giphy.com/media/SpnlWIYMV5PfeItTMt/giphy.gif'],
            ['palabra_id' => '5', 'imagen' => 'https://media.giphy.com/media/YmUjtzs6AeGbANr5pE/giphy.gif'],
            ['palabra_id' => '6', 'imagen' => 'https://media.giphy.com/media/lShUFJwQwdkCXB5N16/giphy.gif'],
            ['palabra_id' => '7', 'imagen' => 'https://media.giphy.com/media/QVOkGWr3onzpdJZXFT/giphy.gif'],
            ['palabra_id' => '8', 'imagen' => 'https://media.giphy.com/media/TiJ8ltlVFJgfPrbchZ/giphy.gif'],
            ['palabra_id' => '8', 'imagen' => 'https://media.giphy.com/media/Xd8AfsPg2w64QSWkfO/giphy.gif'],
            ['palabra_id' => '8', 'imagen' => 'https://media.giphy.com/media/lOOWl1V9f9s6zyg9Ws/giphy.gif'],
            ['palabra_id' => '9', 'imagen' => 'https://media.giphy.com/media/SsrOsRCE0Ot2sQ33uX/giphy.gif'],
            ['palabra_id' => '10', 'imagen' => 'https://media.giphy.com/media/jsI3HeRlCb0gGtrs3G/giphy.gif'],
            ['palabra_id' => '10', 'imagen' => 'https://media.giphy.com/media/JUGwwjVy2spXLrane5/giphy.gif'],
            ['palabra_id' => '11', 'imagen' => 'https://media.giphy.com/media/gKf0oW6HtJRo30Ph5W/giphy.gif'],
            ['palabra_id' => '12', 'imagen' => 'https://media.giphy.com/media/J1dj4d7U0Zk9oehZ8i/giphy.gif'],
            ['palabra_id' => '12', 'imagen' => 'https://media.giphy.com/media/J1dj4d7U0Zk9oehZ8i/giphy.gif'],
            ['palabra_id' => '13', 'imagen' => 'https://media.giphy.com/media/VeOBpLFABZJdaY7bGU/giphy.gif'],
            ['palabra_id' => '13', 'imagen' => 'https://media.giphy.com/media/KgFYebb0ZdDp5jHwj3/giphy.gif'],
            ['palabra_id' => '14', 'imagen' => 'https://media.giphy.com/media/j2qWBsvnYLnBerLpLp/giphy.gif'],
            ['palabra_id' => '15', 'imagen' => 'https://media.giphy.com/media/Q7X3PZb8ktW76TRtP3/giphy.gif'],
            ['palabra_id' => '16', 'imagen' => 'https://media.giphy.com/media/YR8DkyJkBqDrz4hSDE/giphy.gif'],
            ['palabra_id' => '17', 'imagen' => 'https://media.giphy.com/media/igK6zVWp79vZtsIbj2/giphy.gif'],
            ['palabra_id' => '18', 'imagen' => 'https://media.giphy.com/media/QxSHOEdRT1GAB5w7l2/giphy.gif'],
            ['palabra_id' => '19', 'imagen' => 'https://media.giphy.com/media/TId7pHa1Lf9qcqVPZf/giphy.gif'],
            ['palabra_id' => '20', 'imagen' => 'https://media.giphy.com/media/QxT7JFADDbI7arYR0r/giphy.gif'],
            ['palabra_id' => '21', 'imagen' => 'https://media.giphy.com/media/SqZDYdKT2W34806kcy/giphy.gif'],
            ['palabra_id' => '21', 'imagen' => 'https://media.giphy.com/media/jroBTNvLePzh8P48oD/giphy.gif'],
            ['palabra_id' => '22', 'imagen' => 'https://media.giphy.com/media/SqNCaSKj432n4Dsq5y/giphy.gif'],
            ['palabra_id' => '23', 'imagen' => 'https://media.giphy.com/media/hQuQWtOREETp8RNhRf/giphy.gif'],
            ['palabra_id' => '24', 'imagen' => 'https://media.giphy.com/media/kfv1i1zt4yj27dwie4/giphy.gif'],
            ['palabra_id' => '25', 'imagen' => 'https://media.giphy.com/media/VGW27PrMuRmGUBC3Zb/giphy.gif'],
            ['palabra_id' => '26', 'imagen' => 'https://media.giphy.com/media/d7IRTEParcBOcgjJw1/giphy.gif'],
            ['palabra_id' => '27', 'imagen' => 'https://media.giphy.com/media/cLZOZEPIzuENcfQuG6/giphy.gif'],
            ['palabra_id' => '28', 'imagen' => 'https://media.giphy.com/media/el2JtjTxgoLj43j7Bd/giphy.gif'],
            ['palabra_id' => '29', 'imagen' => 'https://media.giphy.com/media/SSVZWpr6RbBNJAi6ts/giphy.gif'],
            ['palabra_id' => '30', 'imagen' => 'https://media.giphy.com/media/H3Mkta3o1EymEXXAk1/giphy.gif'],
            ['palabra_id' => '31', 'imagen' => 'https://media.giphy.com/media/cjiQZAL7khuEyWTPqJ/giphy.gif'],
            ['palabra_id' => '32', 'imagen' => 'https://media.giphy.com/media/VeSVx4IWfFsmY03Hmn/giphy.gif'],
            ['palabra_id' => '33', 'imagen' => 'https://media.giphy.com/media/ZdyAuP1jj90OTtMF35/giphy.gif'],
            ['palabra_id' => '34', 'imagen' => 'https://media.giphy.com/media/ZeRQ7Nfkq0rPsgmdwD/giphy.gif'],
            ['palabra_id' => '35', 'imagen' => 'https://media.giphy.com/media/YrGqgX4B92m80L8BWC/giphy.gif'],
            ['palabra_id' => '36', 'imagen' => 'https://media.giphy.com/media/Ze8y8KRbFU6N1OQKqx/giphy.gif'],
            ['palabra_id' => '37', 'imagen' => 'https://media.giphy.com/media/ZFhq8l9oirVLHk85kf/giphy.gif'],
            ['palabra_id' => '37', 'imagen' => 'https://media.giphy.com/media/W2KLgmpUE7hDLcCq7J/giphy.gif'],
            ['palabra_id' => '37', 'imagen' => 'https://media.giphy.com/media/Th9nkCR7gsIkjs4axi/giphy.gif'],
            ['palabra_id' => '38', 'imagen' => 'https://media.giphy.com/media/kI2l01CIpsIO59oOuR/giphy.gif'],
            ['palabra_id' => '39', 'imagen' => 'https://media.giphy.com/media/da02LWNu9INnPiY6AA/giphy.gif'],
            ['palabra_id' => '39', 'imagen' => 'https://media.giphy.com/media/Ymz2gRlDhCoX8SDa9E/giphy.gif'],
            ['palabra_id' => '40', 'imagen' => 'https://media.giphy.com/media/h2SciCCy3TooznZENm/giphy.gif'],
            ['palabra_id' => '41', 'imagen' => 'https://media.giphy.com/media/RkczKNjqr7YI2EUPog/giphy.gif'],
            ['palabra_id' => '42', 'imagen' => 'https://media.giphy.com/media/mGVQALjjUee5iJf78u/giphy.gif'],
            ['palabra_id' => '43', 'imagen' => 'https://media.giphy.com/media/SAOSazs3sSMdmZ9pYz/giphy.gif'],
            ['palabra_id' => '44', 'imagen' => 'https://media.giphy.com/media/gjNjf8WGB5C9dw3jo6/giphy.gif'],
            ['palabra_id' => '45', 'imagen' => 'https://media.giphy.com/media/LkrexPHU7KsgeUdzAl/giphy.gif'],
            ['palabra_id' => '46', 'imagen' => 'https://media.giphy.com/media/J4yKgYeQQDJlw4inWr/giphy.gif'],
            ['palabra_id' => '47', 'imagen' => 'https://media.giphy.com/media/LRC3oDuwO42pEZrN8H/giphy.gif'],
            ['palabra_id' => '48', 'imagen' => 'https://media.giphy.com/media/VhWwPBorRqTl5M7oOL/giphy.gif'],
            ['palabra_id' => '49', 'imagen' => 'https://media.giphy.com/media/PnIjcVbVMYrmUU7wWQ/giphy.gif'],
            ['palabra_id' => '49', 'imagen' => 'https://media.giphy.com/media/YnTBaIrO7C9txXCDpi/giphy.gif'],
            ['palabra_id' => '50', 'imagen' => 'https://media.giphy.com/media/mDYjyQgd2ICS9FuQWY/giphy.gif'],
            ['palabra_id' => '51', 'imagen' => 'https://media.giphy.com/media/dAXAsfpmxHmlno2CH7/giphy.gif'],
            ['palabra_id' => '52', 'imagen' => 'https://media.giphy.com/media/ZAvql6xvTZvH9StddZ/giphy.gif'],
            ['palabra_id' => '52', 'imagen' => 'https://media.giphy.com/media/JNxAQU3nLeGISTKUe3/giphy.gif'],
            ['palabra_id' => '53', 'imagen' => 'https://media.giphy.com/media/gk9rVuputnHJCaRke0/giphy.gif'],
            ['palabra_id' => '54', 'imagen' => 'https://media.giphy.com/media/H7rWmZOntuL02y6Efk/giphy.gif'],
            ['palabra_id' => '55', 'imagen' => 'https://media.giphy.com/media/dsoC1GD2gX3RU85Bcw/giphy.gif'],
            ['palabra_id' => '56', 'imagen' => 'https://media.giphy.com/media/LOuqi9s8PXsOBA2bKG/giphy.gif'],
            ['palabra_id' => '57', 'imagen' => 'https://media.giphy.com/media/SXIWA5CBiqyyq5zTEA/giphy.gif'],
            ['palabra_id' => '58', 'imagen' => 'https://media.giphy.com/media/fWpdmS91nS9MHdJNRJ/giphy.gif'],
            ['palabra_id' => '59', 'imagen' => 'https://media.giphy.com/media/kF5GJuvYGvrWUVu5IL/giphy.gif'],
            ['palabra_id' => '60', 'imagen' => 'https://media.giphy.com/media/VEhTsbWO89h0ImILS3/giphy.gif'],
            ['palabra_id' => '61', 'imagen' => 'https://media.giphy.com/media/l1IUro4MinnbNa2SU7/giphy.gif'],
            ['palabra_id' => '62', 'imagen' => 'https://media.giphy.com/media/eIgp2Nxid7Q8azm7us/giphy.gif'],
            ['palabra_id' => '62', 'imagen' => 'https://media.giphy.com/media/RNEG3KRYJjdyyhleHr/giphy.gif'],
            ['palabra_id' => '63', 'imagen' => 'https://media.giphy.com/media/cmezpZeiDqpWZmWG30/giphy.gif'],
            ['palabra_id' => '64', 'imagen' => 'https://media.giphy.com/media/W0cndAPMAPmARbDzsb/giphy.gif'],
            ['palabra_id' => '65', 'imagen' => 'https://media.giphy.com/media/USgICU54UEiZMKTrEs/giphy.gif'],
            ['palabra_id' => '66', 'imagen' => 'https://media.giphy.com/media/dsXWWuj6UJFmuuWUBG/giphy.gif'],
            ['palabra_id' => '66', 'imagen' => 'https://media.giphy.com/media/JrqWhPNG6egA5RCnd7/giphy.gif'],
            ['palabra_id' => '67', 'imagen' => 'https://media.giphy.com/media/Jso4J8eYiBXf4siIjM/giphy.gif'],
            ['palabra_id' => '68', 'imagen' => 'https://media.giphy.com/media/fsPNpZYaEO8rVVh7RL/giphy.gif'],
            ['palabra_id' => '69', 'imagen' => 'https://media.giphy.com/media/dalQRAXHFuDHKNrOQx/giphy.gif'],
            ['palabra_id' => '70', 'imagen' => 'https://media.giphy.com/media/hrLLHoR3pjn5Zv2DeG/giphy.gif'],
            ['palabra_id' => '71', 'imagen' => 'https://media.giphy.com/media/ZZl6w7VFSvZZpibdSn/giphy.gif'],
            ['palabra_id' => '71', 'imagen' => 'https://media.giphy.com/media/UtnAAdrrehqfXGqpFR/giphy.gif'],
            ['palabra_id' => '72', 'imagen' => 'https://media.giphy.com/media/ZA5OtaMMURIf3P7ko2/giphy.gif'],
            ['palabra_id' => '73', 'imagen' => 'https://media.giphy.com/media/THTOrNjXMbofXbQqfD/giphy.gif'],
            ['palabra_id' => '74', 'imagen' => 'https://media.giphy.com/media/ZFWxAJAEzZimU5K1lO/giphy.gif'],
            ['palabra_id' => '75', 'imagen' => 'https://media.giphy.com/media/U3agnLQF9cZnArwuC9/giphy.gif'],
            ['palabra_id' => '76', 'imagen' => 'https://media.giphy.com/media/ch2YQJAt7KttFGUYrj/giphy.gif'],
            ['palabra_id' => '77', 'imagen' => 'https://media.giphy.com/media/Vd2NNqgaEUb0QUb2PN/giphy.gif'],
            ['palabra_id' => '77', 'imagen' => 'https://media.giphy.com/media/H6h2NUsUSeSZacsFVJ/giphy.gif'],
            ['palabra_id' => '77', 'imagen' => 'https://media.giphy.com/media/Tg6xqo1SoabF6n277i/giphy.gif'],
            ['palabra_id' => '78', 'imagen' => 'https://media.giphy.com/media/iIXzVA40riyk5s2bwN/giphy.gif'],
            ['palabra_id' => '79', 'imagen' => 'https://media.giphy.com/media/U4LnmETXEarI9DORH8/giphy.gif'],
            ['palabra_id' => '80', 'imagen' => 'https://media.giphy.com/media/KDgNDoqibl1iyGZk1q/giphy.gif'],
            ['palabra_id' => '81', 'imagen' => 'https://media.giphy.com/media/jSQgmakGZ72agXbsAH/giphy.gif'],
            ['palabra_id' => '82', 'imagen' => 'https://media.giphy.com/media/WsuyiT4e9nngjwNJSe/giphy.gif'],
            ['palabra_id' => '83', 'imagen' => 'https://media.giphy.com/media/lSVHRPG71CCIFfZHVN/giphy.gif'],
            ['palabra_id' => '84', 'imagen' => 'https://media.giphy.com/media/dBNy6NNJzoS1HOQ8CP/giphy.gif'],
            ['palabra_id' => '85', 'imagen' => 'https://media.giphy.com/media/VDda0irikNjuSrRquC/giphy.gif'],
            ['palabra_id' => '86', 'imagen' => 'https://media.giphy.com/media/f8Vk6TqYhdep2h9Ldw/giphy.gif'],
            ['palabra_id' => '87', 'imagen' => 'https://media.giphy.com/media/KZYKlGal6JI4x7jswh/giphy.gif'],
            ['palabra_id' => '87', 'imagen' => 'https://media.giphy.com/media/j6HWlIOlBO0ktCSeGf/giphy.gif'],
            ['palabra_id' => '88', 'imagen' => 'https://media.giphy.com/media/MZWy8jNBbeU4CueRJJ/giphy.gif'],
            ['palabra_id' => '89', 'imagen' => 'https://media.giphy.com/media/KGHAVjzh8lFOU4dfMi/giphy.gif'],
            ['palabra_id' => '89', 'imagen' => 'https://media.giphy.com/media/KySukUMS8CAHg51QY4/giphy.gif'],
        ]);
    }
}
